routes:
  /: home
  /about/:
    data: page.about
    template: about

collections:
  /news/:
    permalink: /news/{slug}/
    data: page.news

taxonomies:
  tag: /news/tag/{slug}/
  # author: /news/author/{slug}/
